# Generated by Django 3.0.7 on 2020-06-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=50)),
                ('ProductDesc', models.CharField(max_length=1000)),
                ('ProductQTY', models.PositiveIntegerField()),
                ('ProductPrice', models.PositiveIntegerField()),
            ],
        ),
    ]
